!!python/object/new:dynamic_reconfigure.encoding.Config
dictitems:
  ADIS_IMU: false
  CAMERA_0_HFLIP: false
  CAMERA_0_VFLIP: false
  CAMERA_1_HFLIP: true
  CAMERA_1_VFLIP: true
  CAMERA_2_HFLIP: false
  CAMERA_2_VFLIP: false
  CAMERA_3_HFLIP: true
  CAMERA_3_VFLIP: true
  CAMERA_4_HFLIP: false
  CAMERA_4_VFLIP: false
  CAMERA_5_HFLIP: true
  CAMERA_5_VFLIP: true
  CAMERA_6_HFLIP: false
  CAMERA_6_VFLIP: false
  CAMERA_7_HFLIP: true
  CAMERA_7_VFLIP: true
  CAMERA_8_HFLIP: false
  CAMERA_8_VFLIP: false
  CAMERA_9_HFLIP: true
  CAMERA_9_VFLIP: true
  CAMERA_AUTOEXP: false
  CAMERA_AUTOG: false
  CAMERA_EXP_CAM0: 340
  CAMERA_EXP_CAM1: 340
  CAMERA_EXP_CAM2: 340
  CAMERA_EXP_CAM3: 340
  CAMERA_EXP_CAM4: 340
  CAMERA_EXP_CAM5: 340
  CAMERA_EXP_CAM6: 340
  CAMERA_EXP_CAM7: 340
  CAMERA_EXP_CAM8: 340
  CAMERA_EXP_CAM9: 340
  CAMERA_G_CAM0: 16
  CAMERA_G_CAM1: 16
  CAMERA_G_CAM2: 16
  CAMERA_G_CAM3: 16
  CAMERA_G_CAM4: 16
  CAMERA_G_CAM5: 16
  CAMERA_G_CAM6: 16
  CAMERA_G_CAM7: 16
  CAMERA_G_CAM8: 16
  CAMERA_G_CAM9: 16
  CAMERA_MAX_E: 378
  CAMERA_MIN_E: 0
  CAMERA_TILE: true
  PRIMARY_CAM_MODE: false
  STEREO_BAYER_D: false
  STEREO_CE_CAM1: false
  STEREO_CE_CAM3: false
  STEREO_CE_CAM5: false
  STEREO_CE_CAM7: false
  STEREO_CE_CAM9: false
  STEREO_FP_CAM1: false
  STEREO_FP_CAM3: false
  STEREO_FP_CAM5: false
  STEREO_FP_CAM7: false
  STEREO_FP_CAM9: false
  STEREO_LR_CAM1: 3
  STEREO_LR_CAM3: 3
  STEREO_LR_CAM5: 3
  STEREO_LR_CAM7: 3
  STEREO_LR_CAM9: 3
  STEREO_OF_CAM1: 0
  STEREO_OF_CAM3: 0
  STEREO_OF_CAM5: 0
  STEREO_OF_CAM7: 0
  STEREO_OF_CAM9: 0
  STEREO_P1_CAM1: 10
  STEREO_P1_CAM3: 10
  STEREO_P1_CAM5: 10
  STEREO_P1_CAM7: 10
  STEREO_P1_CAM9: 10
  STEREO_P2_CAM1: 250
  STEREO_P2_CAM3: 250
  STEREO_P2_CAM5: 250
  STEREO_P2_CAM7: 250
  STEREO_P2_CAM9: 250
  STEREO_RE_CAM1: false
  STEREO_RE_CAM3: false
  STEREO_RE_CAM5: false
  STEREO_RE_CAM7: false
  STEREO_RE_CAM9: false
  STEREO_TH_CAM1: 140
  STEREO_TH_CAM3: 140
  STEREO_TH_CAM5: 140
  STEREO_TH_CAM7: 140
  STEREO_TH_CAM9: 140
  groups: !!python/object/new:dynamic_reconfigure.encoding.Config
    dictitems:
      ADIS_IMU: false
      CAMERA_0_HFLIP: false
      CAMERA_0_VFLIP: false
      CAMERA_1_HFLIP: true
      CAMERA_1_VFLIP: true
      CAMERA_2_HFLIP: false
      CAMERA_2_VFLIP: false
      CAMERA_3_HFLIP: true
      CAMERA_3_VFLIP: true
      CAMERA_4_HFLIP: false
      CAMERA_4_VFLIP: false
      CAMERA_5_HFLIP: true
      CAMERA_5_VFLIP: true
      CAMERA_6_HFLIP: false
      CAMERA_6_VFLIP: false
      CAMERA_7_HFLIP: true
      CAMERA_7_VFLIP: true
      CAMERA_8_HFLIP: false
      CAMERA_8_VFLIP: false
      CAMERA_9_HFLIP: true
      CAMERA_9_VFLIP: true
      CAMERA_AUTOEXP: true
      CAMERA_AUTOG: true
      CAMERA_EXP: 40
      CAMERA_GAIN: 16
      CAMERA_MAX_E: 378
      CAMERA_MIN_E: 0
      CAMERA_TILE: true
      PRIMARY_CAM_MODE: false
      STEREO_BAYER_D: false
      STEREO_CE_CAM1: false
      STEREO_CE_CAM3: false
      STEREO_CE_CAM5: false
      STEREO_CE_CAM7: false
      STEREO_CE_CAM9: false
      STEREO_FP_CAM1: false
      STEREO_FP_CAM3: false
      STEREO_FP_CAM5: false
      STEREO_FP_CAM7: false
      STEREO_FP_CAM9: false
      STEREO_LR_CAM1: 3
      STEREO_LR_CAM3: 3
      STEREO_LR_CAM5: 3
      STEREO_LR_CAM7: 3
      STEREO_LR_CAM9: 3
      STEREO_OF_CAM1: 0
      STEREO_OF_CAM3: 0
      STEREO_OF_CAM5: 0
      STEREO_OF_CAM7: 0
      STEREO_OF_CAM9: 0
      STEREO_P1_CAM1: 10
      STEREO_P1_CAM3: 10
      STEREO_P1_CAM5: 10
      STEREO_P1_CAM7: 10
      STEREO_P1_CAM9: 10
      STEREO_P2_CAM1: 250
      STEREO_P2_CAM3: 250
      STEREO_P2_CAM5: 250
      STEREO_P2_CAM7: 250
      STEREO_P2_CAM9: 250
      STEREO_RE_CAM1: false
      STEREO_RE_CAM3: false
      STEREO_RE_CAM5: false
      STEREO_RE_CAM7: false
      STEREO_RE_CAM9: false
      STEREO_TH_CAM1: 140
      STEREO_TH_CAM3: 140
      STEREO_TH_CAM5: 140
      STEREO_TH_CAM7: 140
      STEREO_TH_CAM9: 140
      groups: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      id: 0
      name: Default
      parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      parent: 0
      state: true
      type: ''
    state: []
state: []
